version: 2

tools:
  golangci-lint: &golangci-lint
    lint-command: "golangci-lint --color never run --out-format line-number --build-tags gomoduleredigo"
    lint-formats:
      - "%f:%l:%c: %m"
      - "%f:%l: %m"

languages:
  go:
    - <<: *golangci-lint
